### ISSUE TITLE
Downloaded audio lengths.

### ISSUE THREAD

**Issue by XinhaoMei** [nateraw/download-musiccaps-dataset#3]
Hi, thanks for sharing this wonderful project.

I tried to download audio clips using the provided scrip.
However, many downloaded aduio clips are 20 seconds long, but I think all audio clips should be 10 seconds long.
Do you have any idea on this?
Thanks in advance!

**Comment by XinhaoMei** [comment]
I have solved this by adding `--force-keyframes-at-cuts` to the command.

**Comment by nateraw** [comment]
I noticed this issue the other day thanks for reporting. That flag seems to work accurately? I was worried the downloaded clips might be wrong, so wasn't sure cutting at keyframes would fix the problem or not.

**Comment by XinhaoMei** [comment]
I think it worked accurately. All the audio clips are 10 seconds long. And I mannualy checked some, they are all correct.

**Comment by nateraw** [comment]
I'm going to update the code here to include that flag then after investigating. Reopening until I do

**Comment by nateraw** [comment]
took me long enough 😂  thanks again @XinhaoMei
